num_workers: 4
num_epochs: 5000
batch_size: 128
pin_memory: True
use_amp: True
opt_level: O1
rate_train: 0.7
balancing: True
num_balancing_samples: 20000

dataset:
  path: /content/dataset.h5
  shape: [4, 466, 566]
  channels: [2]
  targets: [1080Lines, 1400Ripples, Air_Compressor, Blip,
            Chirp, Extremely_Loud, Helix, Koi_Fish, Light_Modulation,
            Low_Frequency_Burst, Low_Frequency_Lines, No_Glitch,
            Power_Line, Repeating_Blips, Scattered_Light, Scratchy,
            Tomte, Violin_Mode, Whistle]
  use_other: True

model:
  name: ResNet34

optim:
  name: Adam
  lr: 1e-4
  weight_decay: 0

checkpoint:
  eval: 10
  save: 50

iic:
  num_classes_over: 50
  rate_labeled: 0.1
  num_heads: 5
  reinitialize_header_weights: False

  ssl:
    weights:
      mi_labeled: 1.0
      mi_labeled_over: 1.0
      mi_unlabeled: 1.0
      mi_unlabeled_over: 1.0
      ce: 1.0

  usl:
    weights:
      mi: 1.0
      mi_over: 1.0

vae:
  usl:
    weights:
      bce: 1.0
      kl_norm: 1.0
