wandb:
  project: kagra-deep
  name: test01
  tags: [vae, usl]
  group: vae

run:
  num_epochs: 1000
  targets: [1080Lines, 1400Ripples, Air_Compressor, Blip,
            Chirp, Extremely_Loud, Helix, Koi_Fish, Light_Modulation,
            Low_Frequency_Burst, Low_Frequency_Lines, No_Glitch,
            Power_Line, Repeating_Blips, Scattered_Light, Scratchy,
            Tomte, Violin_Mode, Whistle, Other]
  use_other: True
  use_channels: [1, 2, 3]
  train_size: 0.7
  use_amp: True
  opt_level: O1
  eval_step: 2

  log_params:
    xt:
      type: grid_image
    z:
      type: tsne

  net:
    name: resnet18
    params:
      in_channels: 3

  model:
    name: m1
    params:
      z_dim: 64

  optim:
    name: Adam
    params:
      lr: 1e-4

  dataset:
    name: hdf5
    params:
      root: /content/dataset_small.h5
      shape: [4, 466, 566]

  sampler:
    name: None
    params:
      num_samples: 12800

  loader:
    params:
      num_workers: 4
      pin_memory: True
      batch_size: 128
