num_workers: 4
num_epochs: 5000
batch_size: 128
pin_memory: True
use_amp: True
opt_level: O1
rate_train: 0.7
balancing: False
num_balancing_samples: 10000

dataset:
  path: /content/dataset.h5
  shape: [4, 466, 566]
  channels: [2]
  targets: [1080Lines, 1400Ripples, Air_Compressor, Blip,
            Chirp, Extremely_Loud, Helix, Koi_Fish, Light_Modulation,
            Low_Frequency_Burst, Low_Frequency_Lines, No_Glitch,
            Power_Line, Repeating_Blips, Scattered_Light, Scratchy,
            Tomte, Violin_Mode, Whistle]
  use_other: True

model:
  name: ResNet18

optim:
  name: Adam
  lr: 1e-4
  weight_decay: 0

checkpoint:
  eval: 5
  save: 50

iic:
  num_classes_over: 50
  num_heads: 5
  reinitialize_header_weights: False
