use_channels: [1,2,3]
targets: [1080Lines, 1400Ripples, Air_Compressor, Blip,
          Chirp, Extremely_Loud, Helix, Koi_Fish,
          Light_Modulation, Low_Frequency_Burst, Low_Frequency_Lines, No_Glitch,
          None_of_the_Above, Paired_Doves, Power_Line, Repeating_Blips,
          Scattered_Light, Scratchy, Tomte, Violin_Mode,
          Wandering_Line, Whistle]
use_other: False
num_classes: 22
dim_z: 64
train_size: 0.7
batch_size: 96
num_workers: 4
lr: 1e-4
num_train_steps: 100
eval_interval: 5
num_epochs: 10000
dataset_root: /home/gen.ueshima/gen/workspace/github/GravitySpy/processed/dataset_small.h5
weights: [1., 1.]

wandb:
  project: kagra-deep
  name: test
  tags: None
  group: test


train:
  batch_size: 128
  num_workers: 4
  pin_memory: True
  drop_last: True

eval:
  batch_size: 128
  num_workers: 4
  pin_memory: True
  drop_last: False
